# Generated by Django 2.2 on 2024-02-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp_api', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
