# Generated by Django 2.2 on 2024-02-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp_api', '0005_task_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_email',
            new_name='email',
        ),
    ]
